CREATE TABLE IF NOT EXISTS terminals (
    id UUID PRIMARY KEY,
    alias VARCHAR(255) UNIQUE NOT NULL,
    role VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    handles TEXT,
    tasks TEXT,
    updated_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS terminal_logs (
    id SERIAL PRIMARY KEY,
    terminal_id UUID NOT NULL REFERENCES terminals(id) ON DELETE CASCADE,
    level VARCHAR(32) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flows (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    specification TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
